apiVersion: apps/v1
kind: Deployment
metadata:
  name: ManagementCenter
  labels:
    app: ManagementCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ManagementCenter
  template:
    metadata:
      labels:
        app: ManagementCenter
    spec:
      containers:
        - name: ManagementCenter
          image: username/ManagementCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5